"""empty message

Revision ID: 03db77e7bb8b
Revises: 6eeb36b49ee7
Create Date: 2026-03-11 15:17:12.305559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03db77e7bb8b'
down_revision = '6eeb36b49ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
