"""empty message

Revision ID: 224d7fca2d60
Revises: 
Create Date: 2026-07-04 15:18:03.907033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224d7fca2d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('default_enrollment_fee', sa.Float(), nullable=True),
    sa.Column('default_monthly_fee', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'club_id', name='unique_category_per_club')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('main_position', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('representative_name', sa.String(length=120), nullable=True),
    sa.Column('representative_phone', sa.String(length=30), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('enrollment_fee', sa.Float(), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('payment_cycle_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_counters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'year', name='unique_receipt_counter_per_club_year')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('club_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'gender', 'category_id', 'club_id', name='unique_team_gender_per_category')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('organizer_name', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('default_referee_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'name', 'start_date', name='unique_tournament_per_club')
    )
    op.create_table('team_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='unique_player_per_team'),
    sa.UniqueConstraint('team_id', 'player_number', name='unique_number_per_team')
    )
    op.create_table('tournament_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('registration_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='unique_team_per_tournament')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_team_id', sa.String(length=36), nullable=True),
    sa.Column('referee_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('opponent_name', sa.String(length=120), nullable=True),
    sa.Column('match_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('home_sets', sa.Integer(), nullable=False),
    sa.Column('opponent_sets', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('match_step', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_team_id'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_team_id'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_team_id', 'player_id', name='unique_player_per_tournament_team')
    )
    op.create_table('training_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('training_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_id', 'player_id', name='unique_player_per_training')
    )
    op.create_table('match_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('is_called', sa.Boolean(), nullable=False),
    sa.Column('attendance_status', sa.String(length=20), nullable=True),
    sa.Column('did_play', sa.Boolean(), nullable=False),
    sa.Column('is_on_court', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_sessions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='unique_player_per_match')
    )
    op.create_table('player_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('tournament_team_id', sa.String(length=36), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('payment_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('paid_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match_sessions.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_team_id'], ['tournament_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('match_player_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_sessions.id'], ),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_substitutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('player_out_id', sa.String(length=36), nullable=False),
    sa.Column('player_in_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_sessions.id'], ),
    sa.ForeignKeyConstraint(['player_in_id'], ['match_players.id'], ),
    sa.ForeignKeyConstraint(['player_out_id'], ['match_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('club_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=40), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('sent_channel', sa.String(length=30), nullable=True),
    sa.Column('sent_to', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['player_payments.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_player_id', sa.String(length=36), nullable=False),
    sa.Column('attacks_total', sa.Integer(), nullable=True),
    sa.Column('attacks_positive', sa.Integer(), nullable=True),
    sa.Column('attacks_neutral', sa.Integer(), nullable=True),
    sa.Column('attacks_errors', sa.Integer(), nullable=True),
    sa.Column('receptions_total', sa.Integer(), nullable=True),
    sa.Column('receptions_positive', sa.Integer(), nullable=True),
    sa.Column('receptions_neutral', sa.Integer(), nullable=True),
    sa.Column('receptions_negative', sa.Integer(), nullable=True),
    sa.Column('defenses_total', sa.Integer(), nullable=True),
    sa.Column('defenses_positive', sa.Integer(), nullable=True),
    sa.Column('defenses_neutral', sa.Integer(), nullable=True),
    sa.Column('defenses_negative', sa.Integer(), nullable=True),
    sa.Column('sets_total', sa.Integer(), nullable=True),
    sa.Column('sets_positive', sa.Integer(), nullable=True),
    sa.Column('sets_neutral', sa.Integer(), nullable=True),
    sa.Column('sets_errors', sa.Integer(), nullable=True),
    sa.Column('serves_total', sa.Integer(), nullable=True),
    sa.Column('serves_in', sa.Integer(), nullable=True),
    sa.Column('serves_aces', sa.Integer(), nullable=True),
    sa.Column('serves_errors', sa.Integer(), nullable=True),
    sa.Column('blocks_total', sa.Integer(), nullable=False),
    sa.Column('blocks_points', sa.Integer(), nullable=True),
    sa.Column('blocks_neutral', sa.Integer(), nullable=False),
    sa.Column('blocks_errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_player_id'], ['match_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match_stats')
    op.drop_table('payment_receipts')
    op.drop_table('match_substitutions')
    op.drop_table('match_events')
    op.drop_table('player_payments')
    op.drop_table('match_players')
    op.drop_table('training_players')
    op.drop_table('tournament_players')
    op.drop_table('match_sessions')
    op.drop_table('attendance')
    op.drop_table('training_sessions')
    op.drop_table('tournament_teams')
    op.drop_table('team_players')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('users')
    op.drop_table('receipt_counters')
    op.drop_table('players')
    op.drop_table('categories')
    op.drop_table('token_blocked_list')
    op.drop_table('clubs')
    # ### end Alembic commands ###
